import { useEffect, useRef, useState } from 'react';
import { Camera, CameraOff, CircleStop, Mic, MicOff, MonitorUp, Phone, Video, X } from 'lucide-react';
import type { SupabaseConfig, SupabaseSession } from '../storage/supabaseStateAdapter';
import type { WorkspaceMember } from '../collaboration/types';
import type { CallParticipant, CallRoom as CallRoomRecord, CallSignal } from '../collaboration/callTypes';
import { createCallRoom, endCallRoom, joinCallRoom, leaveCallRoom, listActiveCallRooms, listCallParticipants, subscribeToCallRoom, type CallSubscription } from '../collaboration/callRoom';
import { createPeerConnection, requestCameraAndMicrophone, requestScreenShare, type WebRtcPeer } from '../collaboration/webrtcPeer';
import { appendSpeechTranscript, type SpeechRecognitionEventLike } from '../voice/speechRecognition';
import { saveMeetingMinute } from '../collaboration/meetingMinutes';
import MeetingConsent from './MeetingConsent';

type SpeechRecognizer = { lang: string; continuous: boolean; interimResults: boolean; onresult: ((event: SpeechRecognitionEventLike) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void; };

type Props = { session: SupabaseSession; config: SupabaseConfig; members: WorkspaceMember[]; onNotify: (message: string) => void };

export default function CallRoom({ session, config, members, onNotify }: Props) {
  const [rooms, setRooms] = useState<CallRoomRecord[]>([]); const [room, setRoom] = useState<CallRoomRecord | null>(null); const [participants, setParticipants] = useState<CallParticipant[]>([]); const [consent, setConsent] = useState<{ room: CallRoomRecord; start: boolean } | null>(null); const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [screenStream, setScreenStream] = useState<MediaStream | null>(null); const [remoteStreams, setRemoteStreams] = useState<Record<string, MediaStream>>({}); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const localStreamRef = useRef<MediaStream | null>(null); const localVideoRef = useRef<HTMLVideoElement>(null); const transcriptRef = useRef(''); const recognizerRef = useRef<SpeechRecognizer | null>(null); const meetingStartedRef = useRef(false); const peersRef = useRef<Record<string, WebRtcPeer>>({}); const subscriptionRef = useRef<CallSubscription | null>(null); const currentMember = members.find((member) => member.userId === session.user.id);

  const refreshRooms = async () => { try { setRooms(await listActiveCallRooms(session, fetch, config)); } catch { /* a temporarily unavailable room list should not block the board */ } };
  useEffect(() => { void refreshRooms(); const timer = window.setInterval(() => void refreshRooms(), 8000); return () => window.clearInterval(timer); }, [session, config]);
  useEffect(() => { if (localVideoRef.current) { localVideoRef.current.srcObject = screenStream ?? localStream; } }, [localStream, screenStream]);
  useEffect(() => () => { subscriptionRef.current?.unsubscribe(); Object.values(peersRef.current).forEach((peer) => peer.close()); localStream?.getTracks().forEach((track) => track.stop()); screenStream?.getTracks().forEach((track) => track.stop()); }, [localStream, screenStream]);

  const beginTranscription = () => { const RecognitionConstructor = window.SpeechRecognition ?? window.webkitSpeechRecognition; if (!RecognitionConstructor) return; const recognition = new RecognitionConstructor() as unknown as SpeechRecognizer; recognition.lang = 'pt-BR'; recognition.continuous = true; recognition.interimResults = true; recognition.onresult = (event) => { transcriptRef.current = appendSpeechTranscript('', event); }; recognizerRef.current = recognition; meetingStartedRef.current = true; try { recognition.start(); } catch { /* reconhecimento já iniciado */ } };
  const finishMinutes = () => { recognizerRef.current?.stop(); recognizerRef.current = null; if (!room || !meetingStartedRef.current) return; const transcript = transcriptRef.current.trim(); const sentences = (transcript.match(/[^.!?]+[.!?]+/g) ?? (transcript ? [transcript] : [])).map((sentence) => sentence.trim()).filter(Boolean).slice(0, 8).map((sentence) => sentence.length > 180 ? `${sentence.slice(0, 177)}…` : sentence); saveMeetingMinute({ id: crypto.randomUUID(), title: `Reunião SoulFork · ${new Date(room.createdAt).toLocaleDateString('pt-BR')}`, startedAt: room.createdAt, endedAt: new Date().toISOString(), participants: participants.map((participant) => participant.displayName), sections: [{ speaker: currentMember?.displayName ?? 'Participantes', text: sentences.join(' ') || 'Nenhum trecho de voz foi transcrito nesta reunião.' }], decisions: [], nextSteps: [] }); transcriptRef.current = ''; meetingStartedRef.current = false; };
  const sendSignal = async (signal: CallSignal) => { await subscriptionRef.current?.sendSignal(signal); };
  const peerFor = (userId: string) => peersRef.current[userId] ?? (peersRef.current[userId] = createPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] }, { onIceCandidate: (candidate) => void sendSignal({ type: 'ice-candidate', from: session.user.id, to: userId, candidate: candidate.toJSON() }), onTrack: (stream) => setRemoteStreams((current) => ({ ...current, [userId]: stream })) }));
  const handleSignal = async (signal: CallSignal) => { if (signal.to !== session.user.id) return; const peer = peerFor(signal.from); if (signal.type === 'offer') { peer.addLocalTracks(localStreamRef.current!); const answer = await peer.acceptOffer(signal.description); await sendSignal({ type: 'answer', from: session.user.id, to: signal.from, description: answer }); } else if (signal.type === 'answer') await peer.acceptAnswer(signal.description); else await peer.addIceCandidate(signal.candidate); };
  const startPeers = async (nextParticipants: CallParticipant[]) => { for (const participant of nextParticipants.filter((item) => item.userId !== session.user.id && session.user.id < item.userId)) { const peer = peerFor(participant.userId); peer.addLocalTracks(localStreamRef.current!); const offer = await peer.createOffer(); await sendSignal({ type: 'offer', from: session.user.id, to: participant.userId, description: offer }); } };
  const enterRoom = async () => { if (!consent) return; setError(''); try { const stream = await requestCameraAndMicrophone(); localStreamRef.current = stream; setLocalStream(stream); const nextRoom = consent.start ? await createCallRoom(configuredWorkspaceId(), session, fetch, config) : consent.room; const participant = await joinCallRoom(nextRoom.id, session, currentMember?.displayName ?? session.user.email ?? 'Membro', fetch, config); const nextParticipants = await listCallParticipants(nextRoom.id, session, fetch, config); setRoom(nextRoom); setParticipants(nextParticipants.some((item) => item.userId === participant.userId) ? nextParticipants : [...nextParticipants, participant]); setOpen(true); setConsent(null); beginTranscription(); const subscription = subscribeToCallRoom(nextRoom.id, session, config, (signal) => void handleSignal(signal), () => undefined); subscriptionRef.current = subscription; await startPeers(nextParticipants); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível entrar na reunião.'); } };
  const leave = async (end = false) => { if (!room) return; finishMinutes(); try { if (end && room.initiatorId === session.user.id) await endCallRoom(room.id, session, fetch, config); else await leaveCallRoom(room.id, session, fetch, config); } catch (caught) { onNotify(caught instanceof Error ? caught.message : 'Falha ao sair da chamada.'); } subscriptionRef.current?.unsubscribe(); Object.values(peersRef.current).forEach((peer) => peer.close()); peersRef.current = {}; localStream?.getTracks().forEach((track) => track.stop()); screenStream?.getTracks().forEach((track) => track.stop()); localStreamRef.current = null; setLocalStream(null); setScreenStream(null); setRemoteStreams({}); setRoom(null); setParticipants([]); setOpen(false); await refreshRooms(); };
  const toggleMicrophone = () => { localStream?.getAudioTracks().forEach((track) => { track.enabled = !track.enabled; setMuted(!track.enabled); }); };
  const toggleCamera = () => { localStream?.getVideoTracks().forEach((track) => { track.enabled = !track.enabled; setCameraOff(!track.enabled); }); };
  const shareScreen = async () => { try { const stream = await requestScreenShare(); setScreenStream(stream); const track = stream.getVideoTracks()[0]; if (track) { Object.values(peersRef.current).forEach((peer) => { void peer.replaceVideoTrack(track); }); track.onended = () => { setScreenStream(null); const cameraTrack = localStreamRef.current?.getVideoTracks()[0]; if (cameraTrack) Object.values(peersRef.current).forEach((peer) => { void peer.replaceVideoTrack(cameraTrack); }); }; } } catch (caught) { onNotify(caught instanceof Error ? caught.message : 'Falha ao compartilhar a tela.'); } };
  const activeRoom = rooms[0];
  return <>{!open && <div className="call-launcher"><div><span className="section-kicker">sala de equipe</span><strong><Video size={16} /> Videochamada</strong>{activeRoom && <small>{activeRoom.initiatorId === session.user.id ? 'Sua sala está aberta' : 'Há uma sala aberta agora'}</small>}</div>{activeRoom ? <button className="button secondary" onClick={() => setConsent({ room: activeRoom, start: false })}>Entrar na chamada</button> : <button className="button primary" onClick={async () => { const draft = { id: '', workspaceId: configuredWorkspaceId(), initiatorId: session.user.id, status: 'active' as const, createdAt: new Date().toISOString() }; setConsent({ room: draft, start: true }); }}>Iniciar chamada</button>}</div>}{error && <p className="call-error" role="alert">{error}</p>}{consent && <MeetingConsent onCancel={() => setConsent(null)} onConfirm={() => void enterRoom()} />}{open && room && <div className="call-overlay"><div className="call-window"><div className="call-head"><div><span className="section-kicker">sala aberta · até 3 pessoas</span><h2>Reunião SoulFork</h2></div><button className="icon-button" onClick={() => void leave()} aria-label="Sair da chamada"><X size={18} /></button></div><div className="call-grid"><div className="video-tile local"><video ref={localVideoRef} autoPlay muted playsInline /><span>Você · {currentMember?.displayName ?? 'Membro'}</span></div>{Object.entries(remoteStreams).map(([userId, stream]) => <RemoteTile key={userId} userId={userId} stream={stream} name={participants.find((item) => item.userId === userId)?.displayName ?? 'Membro'} />)}{participants.filter((item) => !remoteStreams[item.userId] && item.userId !== session.user.id).map((participant) => <div className="video-tile waiting" key={participant.userId}><span>{participant.displayName[0]}</span><small>{participant.displayName} conectando...</small></div>)}</div>{error && <p className="call-error" role="alert">{error}</p>}<div className="call-controls"><button className={muted ? 'is-off' : ''} onClick={toggleMicrophone} aria-label={muted ? 'Ativar microfone' : 'Desativar microfone'}>{muted ? <MicOff size={17} /> : <Mic size={17} />}</button><button className={cameraOff ? 'is-off' : ''} onClick={toggleCamera} aria-label={cameraOff ? 'Ativar câmera' : 'Desativar câmera'}>{cameraOff ? <CameraOff size={17} /> : <Camera size={17} />}</button><button onClick={() => void shareScreen()} aria-label="Compartilhar tela"><MonitorUp size={17} /></button><button className="leave-call" onClick={() => void leave()} aria-label="Sair da chamada"><Phone size={17} /></button>{room.initiatorId === session.user.id && <button className="end-call" onClick={() => void leave(true)} aria-label="Encerrar chamada"><CircleStop size={17} /></button>}</div></div></div>}</>;
}

function RemoteTile({ stream, name, userId }: { stream: MediaStream; name: string; userId: string }) { const ref = useRef<HTMLVideoElement>(null); useEffect(() => { if (ref.current) ref.current.srcObject = stream; }, [stream]); return <div className="video-tile"><video ref={ref} autoPlay playsInline /><span>{name}</span></div>; }
function configuredWorkspaceId() { return '00000000-0000-0000-0000-000000000001'; }
