import { MessageCircle, Send, X } from 'lucide-react';
import { useState } from 'react';
import type { ChatChannel, ChatMessage } from '../collaboration/types';
import VoiceInput from './VoiceInput';

export default function ChatPanel({ channels, messages, activeChannelId, currentUserId, onSelectChannel, onSend, onClose }: { channels: ChatChannel[]; messages: ChatMessage[]; activeChannelId?: string; currentUserId: string; onSelectChannel: (id: string) => void; onSend: (content: string) => void; onClose?: () => void }) {
  const [value, setValue] = useState('');
  const active = activeChannelId ?? channels[0]?.id;
  const submit = () => { if (!value.trim()) return; onSend(value); setValue(''); };
  return <aside className="chat-panel" aria-label="Chat SoulFork"><div className="panel-heading"><div><span className="section-kicker">colaboração</span><h2><MessageCircle size={17} /> Chat</h2></div>{onClose && <button className="icon-button ghost" aria-label="Fechar chat" onClick={onClose}><X size={16} /></button>}</div><div className="chat-channels">{channels.map((channel) => <button className={channel.id === active ? 'active' : ''} key={channel.id} onClick={() => onSelectChannel(channel.id)}>{channel.kind === 'general' ? '# ' : '• '}{channel.name}</button>)}</div><div className="chat-messages">{messages.length ? messages.map((message) => <article className={`chat-message ${message.authorId === currentUserId ? 'mine' : ''}`} key={message.id}><small>{message.authorId === currentUserId ? 'Você' : 'Membro'} · {new Date(message.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</small><p>{message.content}</p></article>) : <p className="chat-empty">Nenhuma mensagem ainda. Comece a conversa.</p>}</div><div className="chat-composer"><div className="voice-field"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder="Escreva uma mensagem..." rows={2} /><VoiceInput value={value} onChange={setValue} ariaLabel="Transcrever mensagem com microfone" /></div><button className="send-button" aria-label="Enviar mensagem" onClick={submit}><Send size={15} /></button></div></aside>;
}
