import { ChevronDown, ChevronLeft, ChevronRight, Inbox, Pencil, Plus, Settings2, Sparkles, Trash2, X, Zap } from 'lucide-react';
import { useState } from 'react';
import VoiceInput from './VoiceInput';
import type { QuickCaptureCommands } from '../domain/types';

type InboxPanelItem = { id: string; title: string; description: string; createdAt?: string; quickCommands?: QuickCaptureCommands };

export default function InboxPanel({ items, onCapture, onConfigure, onPromote, onUpdate = () => undefined, onDelete = () => undefined }: { items: InboxPanelItem[]; onCapture: (title: string) => void; onConfigure: () => void; onPromote: (item: InboxPanelItem) => void; onUpdate?: (item: InboxPanelItem) => void; onDelete?: (item: InboxPanelItem) => void }) {
  const [value, setValue] = useState('');
  const [collapsed, setCollapsed] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState('');
  const submit = () => { if (!value.trim()) return; onCapture(value); setValue(''); };
  const beginEdit = (item: InboxPanelItem) => { setEditingId(item.id); setDraft(item.title); };
  const saveEdit = (item: InboxPanelItem) => { if (!draft.trim()) return; onUpdate({ ...item, title: draft.trim() }); setEditingId(null); };
  const remove = (item: InboxPanelItem) => { if (window.confirm(`Excluir a ideia “${item.title}” da Inbox?`)) onDelete(item); };
  if (collapsed) return <aside className="inbox-panel collapsed"><button className="inbox-collapse-toggle" aria-label="Expandir captura rápida" title="Expandir captura rápida" onClick={() => setCollapsed(false)}><ChevronRight size={18} /><span>Captura rápida</span></button></aside>;
  return <aside className="inbox-panel"><div className="inbox-heading"><div><div className="section-kicker">captura rápida</div><h2><Inbox size={19} /> Inbox</h2></div><div className="inbox-panel-actions"><button className="icon-button ghost" aria-label="Ocultar captura rápida" title="Ocultar captura rápida" onClick={() => setCollapsed(true)}><ChevronLeft size={17} /></button><button className="icon-button ghost" aria-label="Configurar Inbox" onClick={onConfigure}><Settings2 size={17} /></button></div></div><div className="quick-capture"><div className="voice-field"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder="Adicione uma ideia ou tarefa..." rows={2} /><VoiceInput value={value} onChange={setValue} /></div><div className="quick-command-hint">Comandos: <b>/site</b> <b>/Braga</b> <b>/alta</b> <b>/sexta</b></div><div className="quick-bottom"><span><Plus size={17} /> Enter para guardar</span><button className="send-button" onClick={submit} aria-label="Guardar captura"><Zap size={16} /></button></div></div><div className="inbox-list">{items.map((item) => <article className="inbox-item" key={item.id}><div className="inbox-item-top"><Sparkles size={14} /><span>ideia capturada</span><div className="inbox-item-actions"><button className="icon-button ghost" aria-label={`Editar ideia ${item.title}`} onClick={() => beginEdit(item)}><Pencil size={13} /></button><button className="icon-button ghost danger-icon" aria-label={`Excluir ideia ${item.title}`} onClick={() => remove(item)}><Trash2 size={13} /></button></div></div>{editingId === item.id ? <div className="inbox-edit"><div className="voice-field"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} autoFocus rows={3} aria-label="Editar ideia" /><VoiceInput value={draft} onChange={setDraft} /></div><div><button className="text-action" onClick={() => saveEdit(item)}>Salvar</button><button className="text-action muted-action" onClick={() => setEditingId(null)}><X size={13} /> Cancelar</button></div></div> : <><h3>{item.title}</h3><p>{item.description || 'Sem descrição ainda.'}</p><button className="text-action" onClick={() => onPromote(item)}>Organizar no quadro <ChevronDown size={14} /></button></>}</article>)}</div><div className="inbox-footer"><Zap size={16} /><span>Pressione <b>/</b> para capturar de qualquer lugar.</span></div></aside>;
}
