import { Camera, Check, KeyRound, LogOut, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import type { UserProfile } from '../profile/profile';

export function ProfileMenu({ profile, onSettings, onSignOut }: { profile: UserProfile; onSettings: () => void; onSignOut: () => void }) {
  const [open, setOpen] = useState(false);
  return <div className="profile-wrap"><button className="avatar" onClick={() => setOpen((value) => !value)} title="Abrir perfil" aria-label="Abrir perfil">{profile.avatarDataUrl ? <img src={profile.avatarDataUrl} alt="" /> : profile.displayName.slice(0, 2).toUpperCase()}</button>{open && <div className="profile-menu" role="menu"><div className="profile-menu-heading"><span className="profile-menu-avatar">{profile.displayName[0]?.toUpperCase()}</span><span><strong>{profile.displayName}</strong><small>Workspace SoulFork</small></span></div><button onClick={() => { setOpen(false); onSettings(); }}><UserRound size={15} /> Settings</button><button onClick={onSignOut}><LogOut size={15} /> Sair</button></div>}</div>;
}

export default function ProfileSettings({ profile, onClose, onSaveProfile, onSavePassword }: { profile: UserProfile; onClose: () => void; onSaveProfile: (profile: UserProfile) => void; onSavePassword: (password: string) => Promise<void> }) {
  const [draft, setDraft] = useState(profile); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const save = async () => { if (password && (password.length < 8 || password !== confirm)) { setMessage('A nova senha precisa ter 8 caracteres e as duas senhas devem ser iguais.'); return; } setBusy(true); setMessage(''); try { if (password) await onSavePassword(password); onSaveProfile(draft); setMessage('Configurações salvas.'); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Não foi possível salvar as configurações.'); } finally { setBusy(false); } };
  const pickAvatar = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setDraft((current) => ({ ...current, avatarDataUrl: String(reader.result) })); reader.readAsDataURL(file); };
  return <div className="modal-backdrop"><div className="modal settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="modal-head"><div><span className="section-kicker">preferências pessoais</span><h2 id="settings-title">Settings</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar settings"><X size={18} /></button></div><label className="field"><span>Nome exibido</span><div className="settings-name"><span className="profile-menu-avatar">{draft.displayName[0]?.toUpperCase() || '?'}</span><input value={draft.displayName} onChange={(event) => setDraft((current) => ({ ...current, displayName: event.target.value }))} /></div></label><label className="field"><span>Imagem do perfil</span><div className="file-input"><Camera size={16} /><input type="file" accept="image/*" onChange={(event) => pickAvatar(event.target.files?.[0])} /></div></label><div className="settings-divider"><KeyRound size={16} /><strong>Alterar senha</strong></div><label className="field"><span>Nova senha <em>opcional</em></span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Mínimo de 8 caracteres" /></label><label className="field"><span>Confirmar nova senha</span><input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Repita a nova senha" /></label>{message && <p className="settings-message" role="status">{message}</p>}<div className="modal-foot"><span className="auth-hint">As alterações ficam associadas somente ao seu perfil.</span><div><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy || !draft.displayName.trim()} onClick={() => void save()}><Check size={16} /> {busy ? 'Salvando...' : 'Salvar'}</button></div></div></div></div>;
}
