import { Check, UserPlus, X } from 'lucide-react';
import { useState } from 'react';
import type { PresenceStatus, WorkspaceMember } from '../collaboration/types';

export default function WorkspaceMembers({ members, presence, isAdmin, onInvite }: { members: WorkspaceMember[]; presence: Record<string, PresenceStatus>; isAdmin: boolean; onInvite: (email: string, displayName: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!email.trim() || !name.trim()) return; setBusy(true); try { await onInvite(email, name); setEmail(''); setName(''); setOpen(false); } finally { setBusy(false); } };
  return <section className="members-panel" aria-label="Membros do workspace"><div className="panel-heading"><div><span className="section-kicker">equipe interna</span><h2>Membros</h2></div>{isAdmin && <button className="icon-button ghost" aria-label="Convidar membro" onClick={() => setOpen((value) => !value)}><UserPlus size={16} /></button>}</div>{open && <div className="invite-form"><input type="text" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do membro" aria-label="Nome do membro" /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="E-mail do membro" aria-label="E-mail do membro" /><button className="button primary" disabled={busy || !name.trim() || !email.trim()} onClick={() => void submit()}>{busy ? 'Enviando...' : <><Check size={14} /> Enviar convite</>}</button><button className="text-action" onClick={() => setOpen(false)}><X size={13} /> Cancelar</button></div>}<div className="member-list">{members.map((member) => { const status = presence[member.userId] ?? 'offline'; return <div className="member-row" key={member.id}><span className={`presence-dot ${status}`} /><span className="member-name">{member.displayName}</span><span className="member-status">{status}</span></div>; })}</div></section>;
}
