export type MeetingMinuteSection = { speaker: string; text: string };
export type MeetingMinute = { id: string; title: string; startedAt: string; endedAt: string; participants: string[]; sections: MeetingMinuteSection[]; decisions: string[]; nextSteps: string[] };

const STORAGE_KEY = 'soultasks-meeting-minutes-v1';

export function loadMeetingMinutes(): MeetingMinute[] { try { const raw = localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) as MeetingMinute[] : []; } catch { return []; } }
export function saveMeetingMinute(minute: MeetingMinute): MeetingMinute[] { const next = [minute, ...loadMeetingMinutes().filter((item) => item.id !== minute.id)]; localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); window.dispatchEvent(new CustomEvent('soultasks:minutes-updated')); return next; }
export function minuteToHtml(minute: MeetingMinute): string { return `<article><h1>${escapeHtml(minute.title)}</h1><p>${new Date(minute.startedAt).toLocaleString('pt-BR')} · Participantes: ${minute.participants.map(escapeHtml).join(', ')}</p><h2>Resumo por participante</h2><ul>${minute.sections.map((section) => `<li><strong>${escapeHtml(section.speaker)}:</strong> ${escapeHtml(section.text)}</li>`).join('')}</ul><h2>Decisões</h2><ul>${minute.decisions.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul><h2>Próximos passos</h2><ul>${minute.nextSteps.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></article>`; }
export function downloadMinuteHtml(minute: MeetingMinute): void { const blob = new Blob([`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>${escapeHtml(minute.title)}</title><body>${minuteToHtml(minute)}</body></html>`], { type: 'text/html;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${minute.title.toLowerCase().replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'ata-reuniao'}.html`; link.click(); URL.revokeObjectURL(url); }
function escapeHtml(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character] ?? character)); }
